version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ava
    versions:
    - 3.15.0
  - dependency-name: standard
    versions:
    - 16.0.3
  - dependency-name: multiaddr
    versions:
    - 8.1.2
    - 9.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: ini
    versions:
    - 1.3.8
